# -*- coding: utf-8 -*-
"""IoT_lab5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DquMjHjlR5MVB7dWtT7fpHo077FM3z86
"""

pip install AWSIoTPythonSDK

import csv 
import json 

def csv_to_json(csvFilePath, jsonFilePath):
    jsonArray = []
      
    #read csv file
    with open(csvFilePath, encoding='utf-8') as csvf: 
        #load csv file data using csv library's dictionary reader
        csvReader = csv.DictReader(csvf) 
        
        #convert each csv row into python dict
        for row in csvReader: 
            #add this python dict to json array
            jsonArray.append(row)
  
    #convert python jsonArray to JSON String and write to file
    with open(jsonFilePath, 'w', encoding='utf-8') as jsonf: 
        jsonString = json.dumps(jsonArray, indent=4)
        jsonf.write(jsonString)
          
csvFilePath = r'beach_weather_stations.csv'
jsonFilePath = r'beach_weather_stations.json'
csv_to_json(csvFilePath, jsonFilePath)

# -*- coding: utf-8 -*-
"""
Created on Wed Jan 27 10:02:20 2021

@author: Chirag
"""


from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient
import sys
import pandas as pd
import json

myMQTTClient = AWSIoTMQTTClient("lab1_thing")

myMQTTClient.configureEndpoint("a278h0kf2bfot2-ats.iot.us-east-2.amazonaws.com", 8883)
myMQTTClient.configureCredentials("./AmazonRootCA1.pem","./e66b73b0c7-private.pem.key", "./e66b73b0c7-certificate.pem.crt")

myMQTTClient.connect()
print("Client Connected")

with open('Lab5_csvjson.json') as f:
    jsonObject = json.load(f)
for key in jsonObject:
    msg=json.dumps(key)
        
    #msg = '{"station_name": "marmik","measurement_timestamp": "2015-05-22T15:00:00","wet_bulb_temperature": "7.0"}'
    topic = "tt1"
    myMQTTClient.publish(topic, msg, 0)  
    print("Message Sent")

myMQTTClient.disconnect()
print("Client Disconnected")